@baseUrl = http://localhost:4004/odata/v4/catalog

### Get service metadata
GET {{baseUrl}}/$metadata

### Get all Books
GET {{baseUrl}}/Books


### Get all Authors
GET {{baseUrl}}/Authors


### Get all Users
GET {{baseUrl}}/Users


### Get BudgetUsers
GET {{baseUrl}}/BudgetUsers


### Get Orders
GET {{baseUrl}}/Orders


### Get PurchaseLogs
GET {{baseUrl}}/PurchaseLogs


### Get Suppliers
GET {{baseUrl}}/Suppliers


### Create a valid Author
POST {{baseUrl}}/Authors
Content-Type: application/json

{
    "name": "George Orwell",
    "country": "GB"
}


### Invalid country
POST {{baseUrl}}/Authors
Content-Type: application/json

{
    "name": "Test Author",
    "country": "rwanda"
}


### 7. CREATE BOOK - VALID
POST {{baseUrl}}/Books
Content-Type: application/json

{
    "title": "My Test Book",
    "description": "A test book for the CAP project",
    "price": 50,
    "stock": 10,
    "author_ID": "AUTHOR_ID_HERE"
}





### Restock a Book
POST {{baseUrl}}/Books(BOOK_ID_HERE)/restock
Content-Type: application/json

{
    "amount": 5
}




### 12. CREATE ORDER - VALID
POST {{baseUrl}}/Orders
Content-Type: application/json

{
    "orderDate": "2026-09-16",
    "user_ID": "USER_ID_HERE",
    "items": [
        {
            "quantity": 2,
            "book_ID": "BOOK_ID_HERE"
        }
    ]
}

### 12. CREATE ORDER - VALID
POST {{baseUrl}}/Orders
Content-Type: application/json

{
    "orderDate": "2026-09-16",
    "user_ID": "USER_ID_HERE",
    "items": [
        {
            "quantity": 2,
            "book_ID": "BOOK_ID_HERE"
        },
        {
            "quantity": 3,
            "book_ID": "BOOK_ID_HERE"
        }
    ]
}





### Check Orders
GET {{baseUrl}}/Orders


### Cancel Order
POST {{baseUrl}}/Orders(ORDER_ID_HERE)/cancelOrder



### Get non-blocked suppliers
GET {{baseUrl}}/Suppliers?$filter=BusinessPartnerIsBlocked eq false



### Select specific Supplier fields
GET {{baseUrl}}/Suppliers?$select=BusinessPartner,BusinessPartnerFullName



### Order Suppliers by name
GET {{baseUrl}}/Suppliers?$orderby=BusinessPartnerFullName


